### ISSUE TITLE
Item duplication / not being removed from chest upon sale {1.3.0}

### ISSUE THREAD

**Issue by waffleston** [SparklingComet/TradeShop#1]
```
Using: git-Spigot-b32c8f8-4d3bf20 (MC: 1.11.2)
Other plugins: WorldEdit, Multiverse-Core, Multiverse-Portals, MassiveCore, Factions
```
There appears to be a glitch involving  item_id:**sub_id**.

Placing only "Polished Andesite" inside a chest selling "Stone" will result in the purchaser being given a "Stone", and the "Polished Andesite" not being removed from the seller's chest.  

This also works conversely: Having only "Polished Andesite" in your inventory and buying something that costs "Stone", will result in the "Polished Andesite" remaining in your inventory while still receiving the item.  

_This could be used by players to duplicate items or sell players items that they do not have._

**Comment by SparklingComet** [comment]
Thank you for your report.
Is any stacktrace being thrown upon the trade?

**Comment by waffleston** [comment]
No, there is not.

**Comment by SparklingComet** [comment]
Okay, I will make sure to upload a patch ASAP.

**Comment by SparklingComet** [comment]
@KillerOfPie , was this fixed in your patch? If yes, the latest JAR from SpigotMC should contain the fix.

**Comment by waffleston** [comment]
The issue was partially fixed - the items are now exchanged and not duplicated or transmuted.  However, a chest selling "Stone" that contains "Polished Andesite" instead of "Stone" will give the player "Polished Andesite".  

The converse still applies as well; a shop taking "Stone" will accept "Polished Andesite" as payment.

**Comment by SparklingComet** [comment]
I see. And you are sure it was not fixed in yesterday's patch?

**Comment by waffleston** [comment]
Yes, I grabbed the jar from spigot - it's named "tradeshop-1.4.0-BETA.jar", but the version text under "/tradeshop help" is "Tradeshop v1.3.0 by Lori00".

**Comment by SparklingComet** [comment]
That is a distraction, you actually downloaded build 1.4.0-BETA. Will fix immediately, but you will need to wait for build 1.4.1 to see the correct version.

**Comment by KillerOfPie** [comment]
Without a complete rewrite of the plugin this is the best that can be done as andesite is just a data value of Stone. So for now the best we can do is no duplication of items.

**Comment by SparklingComet** [comment]
@KillerOfPie andesite is the same Material as Stone, but the durability is different. ItemStack#getDurability() returns different values (if it's a tool such as a spade or a fishing rod, the actual durability is returned, otherwise, it's 0 for stone, 1 for andesite, etc).

All we have to do is write a function that compares these and this issue is fixed.

**Comment by KillerOfPie** [comment]
@SparklingComet very aware of how they come out it was more of putting them on the sign although @waffleston did it a way I couldn't think of when i was initially making the update

**Comment by SparklingComet** [comment]
Closing as it was fixed in #5 and subsequentially #6 .
