### ISSUE TITLE
[BUG] Sign targeting issue for commands that check if a player is looking at it.

### ISSUE THREAD

**Issue by VanirDev** [SparklingComet/TradeShop#69]
I brought this issue up in the TradeShop Help discord server, and figured out the cause in the process of identifying the problem.

Currently, it seems that all commands which require a player to look at a sign, such as **setProduct, setCost, what** etc, all use a method that draws a path from the playerview, and uses the first sign that is hit by this check, within range. While this is direct and functional, I've found some edge cases which have caused my players some serious issues. I've doodled a few hitboxes on some screenshots to clarify the problem.

![Hitbox1](https://user-images.githubusercontent.com/36479515/73698748-e7dba300-46d9-11ea-9902-b33da4d49c11.png)
![Hitbox2](https://user-images.githubusercontent.com/36479515/73698764-f033de00-46d9-11ea-9c06-08635a22b49f.png)
![Hitbox3](https://user-images.githubusercontent.com/36479515/73698772-f5912880-46d9-11ea-9983-9ee914b81243.png)

The issue seems to be that a sign registers based on a block-sized hitbox, rather than the hitbox of the sign itself. This means that while a player may be looking at a sign, and have it outlined as usual, thinking they are looking at it, they're actually targeting the other sign, meaning that their command will not work. This is worst with the vertical example, where players will not realise this quirk and just be unable to use commands on the lower of the two signs.

I'm not sure how easily the spigot API will let you remedy this, or if the reliance on this raycast solution needs to be swapped out for a more robust interaction method, but it's causing issues and creating a lot of confusion.

Thanks for the great work you've done so far!

**Comment by KillerOfPie** [comment]
getTargetBlockExact​(int maxDistance)
getLineOfSight​(Set<Material> transparent, int maxDistance)

**Comment by KillerOfPie** [comment]
Used getTargetBlockExact, this should be fixed, let me know if it continues to be a problem.

**Comment by ebaldino** [comment]
Sorry, I'm not sure how to proceed when posting to a closed issue.
getTargetBlockExact does NOT fix the issue, because it does not accept a list of blocks to ignore. Signs behind a pane of glass, or a block of water, are effectively invisible to getTargetBlockExact.
I've finally decided to try and address this issue for Signboard, so I'm am having to brew my own solution.
